[package]
name = "emulator"
version = "0.1.0"
edition = "2021"

[dependencies]
getrandom = { version = "0.2.15", features = ["js"] }
rust-chip8-opengl = "1.0.3"
wasm-bindgen = "0.2.92"

[lib]
crate-type = ["cdylib"]
